### ISSUE TITLE
Fibonacci.action docs aren't generated

### ISSUE THREAD

**Issue by trainman419** [ros/common_tutorials#11]
As seen on ROS answers: http://answers.ros.org/question/207632/broken-url-in-tutorial/

The docs for Fibonacci.action do not appear to be generated properly.

**Comment by stonier** [comment]
Doesnt seem to be anything odd here..except that it doesnt define CATKIN_DEPENDS. It doesnt strictly need that but its probably why it is not exporting them. Ill make a fix and release shortly.

**Comment by 130s** [comment]
On a related note, on the [wiki page of actionlib_tutorials](http://wiki.ros.org/actionlib_tutorials), there's no link `Msg API`.
Msg API pages seem to be generated ([Indigo](http://docs.ros.org/indigo/api/actionlib_tutorials/html/index-msg.html), [Kinetic](http://docs.ros.org/kinetic/api/actionlib_tutorials/html/index-msg.html), [distro-neutral](http://docs.ros.org/api/actionlib_tutorials/html/index-msg.html)). No idea why.

**Comment by stonier** [comment]
Keep an eye on the `0.1.10` release to see whether the pull request referenced above will fix this issue or not.

**Comment by wjwwood** [comment]
I'm going to close this assuming that this was fixed in `0.1.10`. Please comment here if that is not the case. Thanks!

**Comment by stonier** [comment]
Aye, they are now linked in on the wiki.
