### ISSUE TITLE
Fibonacci Example for SimpleActionServer not working..

### ISSUE THREAD

**Issue by scottnortman** [ros/common_tutorials#22]
Running Win10 + WSL with Ubuntu 16.04 and ROS Lunar

Running unmodified code from 'actionlib_tutorials' to test SImpleActionServer; I start the server with
$ rosrun actionlib_tutorials fibonacci_server.py

In a seperate window, I can see the topics from
$rostopic lsit

Then I start an echo before calling the client:

$ rostopic echo /fibonacci/feedback

Finally, in a separate window I start the client:

$ rosrun actionlib_tutorials fibonacci_client.py

and nothing happens....

After a minute or so, I start to receive warnings in the client AND echo windows:

[WARN] [1534645446.029767]: Inbound TCP/IP connection failed: timed out

Any thoughts as to why the SinmpleActionServer is not working?

**Comment by tfoote** [comment]
Please ask questions on http://answers.ros.org according to our support policy: http://wiki.ros.org/Support We try to keep the issue tracker reserved for bugs and feature developments.
