### ISSUE TITLE
Release common_tutorials to Noetic?

### ISSUE THREAD

**Issue by sloretz** [ros/common_tutorials#25]
Would you mind releasing `common_tutorials` to ROS Noetic? It looks like all of its dependencies have been released, and recursively 10 repos need it.

I'm not sure how much work it will need. At a minimum it needs #24.

**Comment by stonier** [comment]
Pulled across #23 as well. #19 is not ready, it has broken installables.

**Comment by stonier** [comment]
@sloretz bloom does not seem to like #24. I have bloom `v0.9.3-100`.

```
==> git-bloom-generate -y rosrelease noetic --source upstream -i 1
Invalid metapackage:
  Metapackage 'common_tutorials': Invalid CMakeLists.txt
Expected:
<<<cmake_minimum_required(VERSION 2.8.3)
project(common_tutorials)
find_package(catkin REQUIRED)
catkin_metapackage()
>>>
Got:
<<<cmake_minimum_required(VERSION 3.0.2)
project(common_tutorials)
find_package(catkin REQUIRED)
catkin_metapackage()
>>>
```

Any pointers on how to proceed?

**Comment by stonier** [comment]
I suspect it's because I'm running bloom on Ubuntu Bionic. I have until now assumed bloom was distro agnostic, but perhaps it's looking up CMake constraints on the system and reflecting that in this check?

**Comment by sloretz** [comment]
> bloom does not seem to like #24. I have bloom v0.9.3-100

catkin_pkg was updated to allow any CMake version in metapackages. Updating `catkin_pkg` to `0.4.16` will fix the issue.

```console
# Python 2 bloom:
apt-get install python-catkin-pkg-modules
# Python 3 bloom:
apt-get install python3-catkin-pkg-modules
```

**Comment by stonier** [comment]
Ah, noobie mistake, sorry. Got out of the habit of using my update-ros-everything scripts.

`v0.1.12` on it's way ([rosdistro/pull/24334](https://github.com/ros/rosdistro/pull/24334)).
